### ISSUE TITLE
Total fee doesnt match

### ISSUE THREAD

**Issue by grimmlink** [cosmocommerce/magento-alipay#3]
Just upgraded magento-alipay and got this :

    错误描述: 抱歉，该商品的交易金额与原先的不一致，请重新创建交易付款。
    错误代码: TRADE_TOTALFEE_NOT_MATCH

with
Logistics Fees: 0
Logistics Carrier: EXPRESS
Logistics Payment: BUYER_PAY

Why not using total_fee from API instead of price and quantity ? (quantity is always 1)

**Comment by sidealice** [comment]
this has been upgraded. thanks for your comments
