### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by Zifius** [cosmocommerce/magento-alipay#7]
Hello,

I have made some improvements to the extension like converted to the default Magento state/status flow, implemented capturing of the payment and creating an invoice and many other general improvements. Now I wonder if you'd like to accept these and if the current code in this repo is the latest one

Best,
Alex

**Comment by sidealice** [comment]
Hello Zifius,

Welcome your contributions. Please make pull request and we would merged it asap.

**Comment by Zifius** [comment]
Thank you @sidealice, had problems with my computer last week - will submit the PR during this week

Can you create a develop branch I can branch off? My changes are quite big

Thank you,
Alex

**Comment by sidealice** [comment]
I've created a branch named  dev.
Thanks for your contribution!
